### ISSUE TITLE
Properties w/ control vocabulary

### ISSUE THREAD

**Issue by andrecastro0o** [tibonto/aeon#17]
"Controlled vocabulary in MediaWiki:Smw_allows_list_Fee_Currency" ->
 "Controlled vocabulary in MediaWiki:Smw_allows_list_Fee_Currency [[Allows value list::Fee_Currency]]"

**Comment by StroemPhi** [comment]
@andrecastro0o Unfortunately I've mixed this task with the following other commits:

- 981acf2a85414e765c3ecd82d43461e747548747
- 9fcdd7c10405efab64cebec75165a69bace9b23d
- b2af8979f9bdd6c2c6f7882f099405099927e1ec
- 673bc8c1530b6197a263bf0ca4ae9c6cf39f9d1c
- 5cb436e421bf70a52f3e17f20ac8b48050bde56f

Will promise to be more issue bound in the future. Please excuse, I'm still fairly new to the GitHub workflow.
