### ISSUE TITLE
multi line statements brekaing rdflib

### ISSUE THREAD

**Issue by andrecastro0o** [tibonto/aeon#18]
https://github.com/tibonto/aeon/blob/981acf2a85414e765c3ecd82d43461e747548747/aeon.ttl#L778-L789

@StroemPhi the multiline statements are breaking REDFlib `graph.parse` method.

I suggest to change them from
```ttl
                  aeon:SMW_import_info """[[Allows value list::Fee_currency]]
Controlled vocabulary in [[MediaWiki:Smw_allows_list_Fee_currency]]
[[Category:AEON]] [[Category:Imported vocabulary]]""" ,
```
to

```ttl
                  aeon:SMW_import_info "[[Allows value list::Fee_currency]]\nControlled vocabulary in [[MediaWiki:Smw_allows_list_Fee_currency]]\n[[Category:AEON]] [[Category:Imported vocabulary]]",
```

**Comment by andrecastro0o** [comment]
You use the following test to check how rdflib handles it. If :fire_extinguisher: :fire: than something is :fish:hy in TTL. If it is :shushing_face:  that it should be good

```python
import rdflib


def test_ontology_parse():
    graph = rdflib.Graph()
    graph.parse(
        source='https://raw.githubusercontent.com/tibonto/aeon/confIDent/aeon.ttl',
        format='ttl')
    assert graph

test_ontology_parse()
```

**Comment by andrecastro0o** [comment]
Still not quite there:
https://github.com/tibonto/aeon/blob/9fcdd7c10405efab64cebec75165a69bace9b23d/aeon.ttl#L199
`aeon:SMW_import_info "[[Allows value list::has_event_type]]\\nThe allowed value list for this property is defined in\\n[[MediaWiki:Smw_allows_list_has_event_type]].\\n[[Category:AEON]] [[Category:Imported vocabulary]]" .`

I presume it is the `\\n` and perhaps `^M`

If Protegé is not to fussy about it reading the file, I can do the edit in the TTL file directly. It is a simple search and replace `\\n` -> `\n` 
@StroemPhi  let me know

**Comment by andrecastro0o** [comment]
@StroemPhi I am not able to find out where things went wrong, but there a syntax problems between commit:
https://github.com/tibonto/aeon/commit/d1fb524a2e573aeb3f1efaa72ddf09ad956a7e56#diff-cdecefc88ae18c7504f0db92fc6b2378  :+1: 
And
https://github.com/tibonto/aeon/commit/981acf2a85414e765c3ecd82d43461e747548747#diff-cdecefc88ae18c7504f0db92fc6b2378 :-1: 

I have tries to see if I could find the bug, but there is something more than the empty lines inside literals

I think the only way to find out is to
* create a debug branch from https://github.com/tibonto/aeon/commit/d1fb524a2e573aeb3f1efaa72ddf09ad956a7e56#diff-cdecefc88ae18c7504f0db92fc6b2378
* add the changes 1 by one as text to the ttl
* test each change against rdflib
:hole:

**Comment by andrecastro0o** [comment]
Debugging will take place at https://github.com/tibonto/aeon/tree/issue_18_ttl_bug_with_rdflib

**Comment by StroemPhi** [comment]
> I presume it is the `\\n` and perhaps `^M`

It was the weird invisible "^M" linefeed in line 199, which I only see in the git blame but not in sublime nor notepad++.

To test this assumtion I pulled the aeon.ttl again (based on https://github.com/tibonto/aeon/commit/9fcdd7c10405efab64cebec75165a69bace9b23d) and just deleted this linefeed in line 199. With this `test_ontology_parse()` runs without errors.

**Comment by andrecastro0o** [comment]
super! Thank you for looking into it
