### ISSUE TITLE
Get a workflow setup for automatic .ttl creation based on the .owl

### ISSUE THREAD

**Issue by StroemPhi** [tibonto/aeon#20]
In order to be compliant woth the standard OBO workflow we need to have AEON as an owl. The tibonto backend works only with TTL though. Thus we need an automatic conversion of the OWL to TTL so that the tibonto service picks this. THis can also be in a subfolder, as the tibonto scripts will search the whole repo for a TTL.

**Comment by StroemPhi** [comment]
@andrecastro0o I would need your help for this one. But the prio is low atm, so let's schedule this for some time after the stakeholder presentation, I suggest.

**Comment by StroemPhi** [comment]
duplicate of #12

**Comment by andrecastro0o** [comment]
:+1:  RDFlib shoul dbe able to handle it. and maybe we can integrate it with a git hook.
Let's discuss it when is convenient!
