### ISSUE TITLE
Tag relevant classes and properties for subobject template creation in SMW

### ISSUE THREAD

**Issue by StroemPhi** [tibonto/aeon#24]
In order to be able to identify and also automatically create the subobjects we need in the SMW, all classes an properties that should become a subobject need to be tagged in a certain way. 

This way has the syntax [[partOfSubobject::"SUBOBJECT_NAME"]] --> e.g.: [[partOfSubobject::Fee]]

**Comment by andrecastro0o** [comment]
i beleive this is done. hence i am closing it
