### ISSUE TITLE
spaces bug in ttl

### ISSUE THREAD

**Issue by andrecastro0o** [tibonto/aeon#26]
@StroemPhi  The usual bug with spaces in the ttl,  confIDent branch

This bug was not in  the #24 branch, it most have come from commit made  to confIDent before #25 

```  File "/home/andre/Documents/TIB/projects/confiDent/code/ontology2smw/venv/lib/python3.7/site-packages/rdflib/plugins/parsers/notation3.py", line 1623, in BadSyntax
    raise BadSyntax(self._thisDoc, self.lines, argstr, i, msg)
rdflib.plugins.parsers.notation3.BadSyntax: at line 1439 of <>:
Bad syntax (objectList expected) at ^ in:
"...b'ect Contributor]]\n\n\n[[Category:AEON]] [[Category:Imported vo'^b'cabulary]]""" .\n\n\n###  https://github.com/tibonto/aeon#Count'..."
```
I see nothing wrong around https://github.com/tibonto/aeon/blob/3f8c4b653166a5a53493b1a18efbb2db6567e745/aeon.ttl#L1436

Can you please look at it?

**Comment by StroemPhi** [comment]
The problem came with https://github.com/tibonto/aeon/commit/343e61bc13769fe117dcdcfcc6ea04c7096d6df0. Must have been my error of forgetting to select this line to be updated in this commit. I'm sorry!

**Comment by andrecastro0o** [comment]
no worries. thanks for swiftly looking into it
