### ISSUE TITLE
aeon:event_frequency display units::year add to SMW_import_info

### ISSUE THREAD

**Issue by andrecastro0o** [tibonto/aeon#27]
@StroemPhi can you please add to https://github.com/tibonto/aeon/blob/810b455d2d975c6325d52da991abde903d078918/aeon.ttl#L892 `[[Corresponds to::1 month]] [[Corresponds to::1 months]] [[display units::months]]`

**Comment by StroemPhi** [comment]
@andrecastro0o will do, but not open an issue branch for that but push it directly to the ConfIDent branch

**Comment by andrecastro0o** [comment]
@StroemPhi corrected, the unit we are using is months
