### ISSUE TITLE
remove unecessary subobjects annotations

### ISSUE THREAD

**Issue by andrecastro0o** [tibonto/aeon#30]
@StroemPhi 

I noticed that there were a few subobject annotations, when they are not need. In essence in SMW we use subobject if we need:
* more than 1 property to form a unit, which is "read together", ie.  `aeon:metric MyAwesomeMetric  && aeon:Metrci value 1000 ` 
* or if we want it  1 or more properties to for an instance of class (a page without a page)

To assign more than 1 value to the same property, in 1 page, we do not need subobjects.

At the moment I see no need for the subobjects:
```
    Subobject AdditionalProcessName (BFO 0000015)
    Subobject Relation (event)
    Subobject Deadline
    Subobject Contributor
    Subobject Committee
   Subobject Sponsor
  Subobject AdditionalProcessName
```

But correct me if I wrong.

If you agree with this, keep the issue open, and don't clean anything yet.
 I will add more properties where subobject is not required, as I implement it in MW

https://github.com/tibonto/aeon/blob/f8ddc03977aa088e40d826b89eb9113b8adc2640/aeon.ttl#L530

**Comment by StroemPhi** [comment]
@andrecastro0o I agree and will wait until you give me the go to get rif of them.

**Comment by StroemPhi** [comment]
Although the sponsor subobject is aeon:has_sponsor && aeon:sponsor_type.

**Comment by andrecastro0o** [comment]
oh, but Sponsor_type does not have domain:BFO 0000015 so  how can i nfer that it should be within the BFO 0000015/Process template? 
https://www.confident-conference.org/r/vanilla/Property:Sponsor_type
https://www.confident-conference.org/r/vanilla/Help:All_Properties#Domain:BFO_0000015_.28Process.29

**Comment by andrecastro0o** [comment]
updated issue with 
* `aeon:collocated_event_of `
* `aeon:joint_event_of `
* `aeon:umbrella_event_of `
