### ISSUE TITLE
Domainless External IDs

### ISSUE THREAD

**Issue by andrecastro0o** [tibonto/aeon#32]
`aeon:has_WDQID` `aeon:has_GND` `aeon:has_DOI`  have no domain.
How do I know, from the ontology in which classes to use them?

By contrast `aeon:has_ISNI` `aeon:has_ORCHID` `aeon:has_ROR` has domain.

**Comment by StroemPhi** [comment]
@andrecastro0o my idea to not assign a domain is grounded in the fact that e.g. an organization or person can have a WDQID as well as an event or event series. But I guess it seems better to define a union class of all those entities that can have either one of these external IDs.
@mconlon17 what do you think? Is it better to have them domain-less or make union classes?

**Comment by andrecastro0o** [comment]
@StroemPhi to be honest I no longer what context prompted this question. For the moment I would leave as is
