### ISSUE TITLE
add "External formatter URI" property to external identifier properties

### ISSUE THREAD

**Issue by andrecastro0o** [tibonto/aeon#33]
@StroemPhi please integrate to ontology into `aeon:SMW_import_info` property of the properties `aeon:has_DOI`,  `aeon:has_GND` `aeon:has_ISNI` `aeon:has_ORCID` `aeon:has_ROR` `aeon:has_WDQID` the following SMW property and value for [External formatter uri::](https://www.semantic-mediawiki.org/wiki/Help:Special_property_External_formatter_URI) 

Since they have to have  [Has type::External identifier](https://www.semantic-mediawiki.org/wiki/Help:Type_External_identifier)

See example https://www.confident-conference.org/r/vanilla/Property:Has_WDQID

**Comment by StroemPhi** [comment]
@andrecastro0o done with: 4279563280b98621789ca4fc81b3a3700257afcd
