### ISSUE TITLE
remove SMW property Allows value list

### ISSUE THREAD

**Issue by andrecastro0o** [tibonto/aeon#35]
@StroemPhi I would like to remove the `[[Allows value list::Has_fee]] ` from Property definitions, and leave only and annotation like 
`The allowed value list for this property is defined in [[MediaWiki:Smw_allows_list_Has_fee]].`

This is because, while importing external sources, we might get values that are not in `Allows value list` and hence it wont display the value.  We can keep the annotation, so it serves as a guide line, and use it in the forms, but not enforce.

I can do this myself, sub assign the issue to me

These are the properties:
* `aeon:fee_currency`
* `aeon:has_fee`
* `aeon:sponsor_type`

**Comment by andrecastro0o** [comment]
@StroemPhi if you have the change can  you please do this?

**Comment by andrecastro0o** [comment]
@StroemPhi I think I made a mistake. I meant all 
`[[Allows value list::*]]` in aeon ttl as I can do their enforcement in the Form definition. And if an external imported source brings a another value it wont produce an error, which prevents the property value from being display.

I believe  
    aeon:fee_currency
    aeon:has_fee
    aeon:sponsor_type
was a wrong copypasta that came from the subobjects issues.
I am sorry

**Comment by StroemPhi** [comment]
@andrecastro0o but now I can close this richt?
