### ISSUE TITLE
Introduce student fee

### ISSUE THREAD

**Issue by clange** [tibonto/aeon#47]
In addition to 

https://github.com/tibonto/aeon/blob/77a0ce7d192d663a0c0bc83ca149a231af558565/aeon.ttl#L1718-L1719

and

https://github.com/tibonto/aeon/blob/77a0ce7d192d663a0c0bc83ca149a231af558565/aeon.ttl#L1752-L1753

would it make sense to have `Student_Fee`.

Also, what about the hierarchy? Is a member/student fee always a reduced fee?

**Comment by StroemPhi** [comment]
@clange you are right to ask about the student fee. I wasn't sure yet, if the distinctions of fees could be modeled using named individuals. I seems like this is not a good idea and that instead it these types of fees should be subclasses of aeon:Fee. What do you think?
