### ISSUE TITLE
use xsd:dateTimeStamp

### ISSUE THREAD

**Issue by clange** [tibonto/aeon#49]
`xsd:dateTime` like here

https://github.com/tibonto/aeon/blob/77a0ce7d192d663a0c0bc83ca149a231af558565/aeon.ttl#L1740

is not precise because it does not include the timezone. I think we should not allow something like "10:00 in the timezone that was the local time at the event's venue on the given date". Instead, I would recommend `xsd:dateTimeStamp`.

**Comment by StroemPhi** [comment]
fixed with f5f91931341635a39285a1ba6e3b9909f6c57ae7
closed with d2c49a03098b7a020d795c60d7727fa12944a7fd
