### ISSUE TITLE
Add human-readable labels.

### ISSUE THREAD

**Issue by clange** [tibonto/aeon#50]
Many classes, such as

https://github.com/tibonto/aeon/blob/77a0ce7d192d663a0c0bc83ca149a231af558565/aeon.ttl#L1638-L1641

do not have human-readable `rdfs:label`s. I think we'll initially need them in English and German.

**Comment by StroemPhi** [comment]
@clange: see also https://github.com/tibonto/aeon/issues/50 
Will pull this up on my todo list!

**Comment by StroemPhi** [comment]
@clange although in the example above the non-human readable label is the label of the parent class. Unfortunately, I cannot change this and at the same time adhere to the style principles of OBO (http://www.obofoundry.org/principles/fp-003-uris.html).

**Comment by StroemPhi** [comment]
sticking to OBO standard of havin term IDs in IRI and rdfs:label for the labels, as labels might change but the entity/property denoted with the term does not
