### ISSUE TITLE
EventType subClassOf skos:Concept?

### ISSUE THREAD

**Issue by clange** [tibonto/aeon#51]
What is the use case for this?

https://github.com/tibonto/aeon/blob/77a0ce7d192d663a0c0bc83ca149a231af558565/aeon.ttl#L1467

It looks strange to me, but without knowing the intended use case I can't tell whether it's good or bad.

**Comment by StroemPhi** [comment]
@clange: The idea behing making the EventType a skos:Concept is rooted in the fact, that there are no clear discriminators with which we can make a distinction that will hold in a global context as the definitions for the various event types vary depending on the sociocultural context.

**Comment by clange** [comment]
@StroemPhi looking at this once more, I think what you meant is `aeon:EventType rdf:type skos:Concept`, i.e., instance instead of subclass.

**Comment by StroemPhi** [comment]
@clange the instances of `aeon:EventType` are Conference, Workshop, etc. and yes they are suppose to be instances of skos:Concept so for example `aeon:Conference rdf:type skos:Concept`.
But how can I then group them in AEON if I can't make aeon:EventType a subclass of skos:Concept? 
Or does that mean that we'd just have many individuals for skos:Concept and the range of aeon:has_event_type would be skos:Concept?

**Comment by StroemPhi** [comment]
@clange the same pattern holds true for AEON_0000027 ('academic field') & AEON_0000028 ('topic'). If this can be modeled better wrt the fact that they we need some way to bundle these named individuals of skos:Concept that are event types, academic fields or topics, I'm happy to change this.

**Comment by StroemPhi** [comment]
Acoording to the [SKOS specs](https://www.w3.org/TR/skos-reference/#L879), I should have been using [skos:Collection](http://www.w3.org/2004/02/skos/core#Collection) alongside with the [skos:memeber](http://www.w3.org/2004/02/skos/core#member ) relation instead of [skos:Concept](http://www.w3.org/2004/02/skos/core#Concept) in order to be able to group the skos:Concepts of academic field, event type and topic.

Will be fixed in:

**Comment by StroemPhi** [comment]
a3f4a29 is the result of rebaseing this branch on https://github.com/tibonto/aeon/tree/issue6-definitions-and-descriptions, as this contains more up to date definitions.

**Comment by StroemPhi** [comment]
So the idea is that event type becomes an iao:plan specification, as the type of an academic event is made up by the sociocultural format the organizers chose. The good thing about it being a plan spec is that this entails action and objective specifications. When we now also add to have condition specifications as part of the academic event type specification, we have everything needed to describe the plans of the organizers.

The only thing I didn't think tzhrough before pushing is that the subclasses of academic event should not be logically defined using the named individuals for the event type specs defined in AEON via the rdfs:equivalentTo but rather the rdfs:subclassOF axiom. Will fix this now.
