### ISSUE TITLE
change list 

### ISSUE THREAD

**Issue by andrecastro0o** [tibonto/aeon#66]
@StroemPhi it would be useful if we could have somewhere a change list from previous properties names to current ones, otherwise I will need to do a lot of digging on the ontology to find out what Terms changed and to what did they change.

**Comment by StroemPhi** [comment]
@andrecastro0o is a txt like this ok?:
```
Changes of classes and properties in AEON

deleted parent classes due to BFO subsumtion:
	aeon:Location --> bfo:0000029	rdfs:label 'site'
	aeon:PhysicalLocation --> obo:GAZ_00000448 rdfs:label 'geographic location'


renamed entities due to BFO/OBO naming conventions:
	aeon:Event --> aeon:AEON_0000001	rdfs:label 'academic event'
```

**Comment by andrecastro0o** [comment]
yes. But it can be even simpler, so that i can look at it and see right away what needs to be changed in the wiki forms + templates. I don't need to know why :smile: :hammer:

Perhaps
```
CHANGE LIST: version

aeon:Event --> aeon:AEON_0000001
aeon:PhysicalLocation --> obo:GAZ_00000448
aeon:Event --> aeon:AEON_0000001
aeon:XYZ --> DELETED   
```

**Comment by StroemPhi** [comment]
@andrecastro0o if it's suposse to be so compact and version specific, I propose to put it in the release description instead of having another file. What do you say?

**Comment by StroemPhi** [comment]
Rethinking my last comment, I add that this must also be in a file to see all the changes at once, off course. Sorry the coffee didn't kick in yet.

**Comment by andrecastro0o** [comment]
they call all go into a singe file CHANGELOG.txt or something like it

```
Version   Date
ADDED --> aeon:AEON_666
aeon:Event --> aeon:AEON_0000001
aeon:PhysicalLocation --> obo:GAZ_00000448
aeon:Event --> aeon:AEON_0000001
aeon:XYZ --> DELETED   
```

**Comment by StroemPhi** [comment]
rolling change log is here: https://github.com/tibonto/aeon/blob/master/change_log.txt
