### ISSUE TITLE
add skos prefix to aeon.ttl

### ISSUE THREAD

**Issue by andrecastro0o** [tibonto/aeon#69]
@StroemPhi would it possible to add `@prefix skos: <http://www.w3.org/2004/02/skos/core#> .` to aeon.ttl

in running https://github.com/TIBHannover/ontology2smw I using the ontology prefixes to generate the SMW import page, and if the prefix is missing for a Term I am getting:
`Error: The ontology you are parsing has no prefix for the term: http://www.w3.org/2004/02/skos/core#Concept`

I will have to think of a way to get/create the prefixes when they are not declared in the ontology, but for the moment think it is just easier to just added it in to aeon.ttl

**Comment by StroemPhi** [comment]
@andrecastro0o done, new release will be there in a few minutes

**Comment by StroemPhi** [comment]
https://github.com/tibonto/aeon/releases/tag/v0.2.9
