### ISSUE TITLE
clarify difference between aeon:is_about and aeon:subject

### ISSUE THREAD

**Issue by andrecastro0o** [tibonto/aeon#75]
https://github.com/tibonto/aeon/blob/f8514983fc616721f44f483e62b5fa236aa520d0/aeon.ttl#L2360

https://github.com/tibonto/aeon/blob/f8514983fc616721f44f483e62b5fa236aa520d0/aeon.ttl#L1667

**Comment by StroemPhi** [comment]
@andrecastro0o the one is an ObjectProperty to relate to the subject class, whereas the DatatypeProperty wa sintended to be used for the literal value. But I need to overthing my understanding regarding the usage of DatatypeProperties and hope that @clange can help me with that sometime soon.

Anyway aeon:is_about has been deleted in the wake of subsuming the Dataproperties under BFO --> c46bb680f30fe4b0345ce21f1356f7236c1748d0
