### ISSUE TITLE
 Create github action that converts aeon.ttl to aeon.owl using robot 

### ISSUE THREAD

**Issue by andrecastro0o** [tibonto/aeon#87]
unlike #72 that required users to have robot installed to convert the ttl to an owl, whenever a commit was made,
I am thinking of using github actions to
- [x] create new action
- [ ] use [Action: build artifact](https://github.com/marketplace/actions/upload-a-build-artifact) to copy a file from the build, eventually the owl
- [ ] install robot ( which can be seen in https://github.com/information-artifact-ontology/IAO/blob/1b4a255e8327da3ea924b4cc099840fe0dd729e4/Makefile#L48-L61)
- [ ] do the conversion with robot `robot convert --input aeon.ttl --format owl --output aeon.owl; git add aeon.owl`

**Comment by andrecastro0o** [comment]
As show in https://github.com/tibonto/aeon/actions/runs/423451889 resulting artifact is added NOT to repository, but to actions build artifact.
More documentation about it in https://docs.github.com/en/free-pro-team@latest/actions/guides/storing-workflow-data-as-artifacts

Now the issue is how to add the artifact to the repository. An option could be to use [git-auto-commit](https://github.com/marketplace/actions/git-auto-commit) to perform that change, let's try it

**Comment by StroemPhi** [comment]
this can be closed, as we've switched to an ODK based workflow with #149
