### ISSUE TITLE
Remove SMW related annotation properties

### ISSUE THREAD

**Issue by StroemPhi** [tibonto/aeon#98]
We had defined annotation properties (`aeon:SMW_datatype`, `aeon:SMW_import_info`, `aeon:WikidataLabel` & `aeon:WikidataURI`) which are needed only in the context of the ConfIDent project and where meant to ease the import of AEON into a clean SMW instance. For the general use of AEON this is not need and also the [ontology2smw](https://github.com/TIBHannover/ontology2smw) tool used for an automated ontology import into a SMW doesn't seem to need this anymore. 

Therefore those properties should be purged from AEON and might only be implemented in a fork ment to be used as an application ontology.

**Comment by andrecastro0o** [comment]
@StroemPhi  I wonder if [ROBOT remove](http://robot.obolibrary.org/remove) can be used to automate this task

**Comment by StroemPhi** [comment]
@andrecastro0o  oohh, I like you're thinking! If you have the time and energy to try, feel free ;)

**Comment by andrecastro0o** [comment]
The is a issue on robot handling of the TTL . I reported it at https://github.com/ontodev/robot/issues/846

**Comment by StroemPhi** [comment]
@andrecastro0o  thank you!

**Comment by andrecastro0o** [comment]
from the terms removal in

`robot diff --left aeon.ttl --right aeon_no_SMW.ttl --output changes.txt`
detected the following changes 
[changes.txt](https://github.com/tibonto/aeon/files/6396762/changes.txt)
